### ISSUE TITLE
Sql & Javascript Date / Timezone Interaction

### ISSUE THREAD

**Issue by mamaso** [Azure/azure-mobile-apps-node#225] opened 2015-11-24 20:50 UTC
Dates in javascript are represented with users local timezone offset, even if specified as UTC.

When adding to database a date like 2015-12-01 00:00:00 becomes 12015-11-30 16:00:00 +8:00 (the same time, but represented in PST with offset)

This means that currently, all dates handled by a server will be stored with that server's local timezone offset.  This behavior may not be what we want.  It makes seeding / etc break with e2e tests.

**Comment by danderson00** [comment] 2015-11-25 18:36
I can confirm that this only affects dates that are set on the server side with Javascript, it does not affect dates set on the client, i.e. the REST API interprets dates correctly.

I am happy to go to beta with this issue, but I will continue to investigate, hopefully we will have a fix before then.

**Comment by phvannor** [comment] 2015-11-25 18:49
What will updatedAt and createdAt have?  Most of the dates we care about are set server side.

**Comment by danderson00** [comment] 2015-11-25 18:52
These are set by a trigger and database default respectively, so they are OK.

**Comment by danderson00** [comment] 2015-11-25 19:11
So... Turns out this is the same behavior as V1. Steps to repro:

- Create mobile app / service
- Create todoitem table with portal
- Download managed todo client, create new date column, set explicitly to new Date(2015, 1, 1) on client when inserting
- Insert item - item is returned (displayed) as expected - 1/1/2015 12:00:00 AM
- Change server script to set date on insert to new Date(2015, 0, 1) (Javascript uses 0 based month)
- Insert item - item is returned (displayed) as 12/31/2014 4:00:00 PM

This behavior is consistent across mobile services and apps, so I'm assuming as this was never dealt with that no customers ever brought it up.

Therefore, closing issue.

**Closed by danderson00** 2015-11-25 19:11 UTC
Labels: bug

**Comment by danderson00** [comment] 2015-11-25 19:14
A side note - we do need to figure out how to seed data with correct dates...
