### ISSUE TITLE
Insert failure error message is confusing when dynamic schema is turned on

### ISSUE THREAD

**Issue by m-andersen** [Azure/azure-mobile-apps-node#390] opened 2016-03-24 16:49 UTC
I use the table.dynamicSchema = true in all my tables while doing devolpment. I run a local server version and have set data connector pointing to my SQL server in Azure. 
When I try to insert a new item to a table it throws an exception and I can't continue.
What is funny is that the same statement seems to work when executing from azurewebsites.net (ALTER table is executed). Please fix this.

2016-03-24T16:33:12.702Z - debug: SQL statement failed - Invalid column name 'myf_uniq_user_id'.: INSERT INTO [dbo].[MyfStorageRooms] ([id],[myf_uniq_user_id]) VALUES (@id,@myf_uniq_user_id); SELECT * FROM [dbo].[MyfStorageRooms] WHERE [id] = @id with parameters [{"name":"id","value":"7888fbf3-d94c-4387-8a13-19dc508b2fc2","type":{"length":255}},{"name":"myf_uniq_user_id","value":"martin","type":{}}]

**Comment by danderson00** [comment] 2016-03-24 18:29
Hi @m-andersen, thanks for reporting this. It's hard to tell what's going on, it does look like dynamic schema is being turned off when running locally. Could you possibly set the logging level to silly by adding the command line option `---logging.level silly` and copying the relevant results here?

**Comment by m-andersen** [comment] 2016-03-24 18:34
Here is the whole output

2016-03-24T18:33:36.114Z - silly: Executing SQL statement INSERT INTO [dbo].[MyfStorageRooms] ([_id],[data_id],[tester],[myf_household_id],[id],[myf_uniq_user_id]) VALUES (@_id,@data_id,@tester,@myf_household_id,@id,@myf_uniq_user_id); SELECT * FROM [dbo].[MyfStorageRooms] WHERE [id] = @id with parameters [{"name":"_id","value":"123456","type":{}},{"name":"data_id","value":"5456","type":{}},{"name":"tester","value":"1234","type":{}},{"name":"myf_household_id","value":null},{"name":"id","value":"320bf3e3-6266-40c3-8add-fbefee7a9288","type":{"length":255}},{"name":"myf_uniq_user_id","value":"sid:3e2d36c26fc1a21973ddae5e8418bc0b","type":{}}]
2016-03-24T18:33:36.185Z - debug: SQL statement failed - Invalid column name 'tester'.: INSERT INTO [dbo].[MyfStorageRooms] ([_id],[data_id],[tester],[myf_household_id],[id],[myf_uniq_user_id]) VALUES (@_id,@data_id,@tester,@myf_household_id,@id,@myf_uniq_user_id); SELECT * FROM [dbo].[MyfStorageRooms] WHERE [id] = @id with parameters [{"name":"_id","value":"123456","type":{}},{"name":"data_id","value":"5456","type":{}},{"name":"tester","value":"1234","type":{}},{"name":"myf_household_id","value":null},{"name":"id","value":"320bf3e3-6266-40c3-8add-fbefee7a9288","type":{"length":255}},{"name":"myf_uniq_user_id","value":"sid:3e2d36c26fc1a21973ddae5e8418bc0b","type":{}}]

**Comment by danderson00** [comment] 2016-03-24 18:54
Does the output show the ALTER TABLE statements executed immediately after? If not, dynamic schema is definitely not turned on. What does the table definition look like?

**Comment by m-andersen** [comment] 2016-03-24 19:05
Unfortunately no ALTER TABLE is following. I was expecting that to be executed, just like when running in the cloud.
Table definition file in the tables dir is (here the .js file)

var table = module.exports = require('azure-mobile-apps').table();

table.dynamicSchema = true;

**Comment by danderson00** [comment] 2016-03-24 22:38
I'm unable to reproduce the behavior with a simple mobile app. Perhaps you could share your solution in a ZIP file and I can take a closer look?

**Comment by m-andersen** [comment] 2016-03-25 10:28
Aha. I got further now and managed to get through it. This is what happens:
- I call table.insert(item) to insert a new row in the table
- As there is a new column name, it will be rejected (a JavaScript promise fails)
- An exception in the debugger (I'm using Visual studio code for MAC) is triggered, as the debugger is configured by default to have breakpoints at "Uncaught Exception". The exception happens in promises.js, line 38, triggered from src/data/mssql/execute.js, line 55 (return promises.rejected(err);)
- When the exception happens, I now press F5 to continue. It actually now starts to do ALTER TABLE and then re-inserts the item successfully.

It was not clear to me that this would generate an exception in the framework. Perhaps it could be handled differently as this is a bit of a false alarm, since dynamicSchema is enabled and it actually completes in the end.
This is the output after I let debugger continue 

2016-03-25T10:12:53.312Z - silly: Executing SQL statement INSERT INTO [dbo].[MyfStorageRooms] ([id],[new_user_id]) VALUES (@id,@new_user_id); SELECT * FROM [dbo].[MyfStorageRooms] WHERE [id] = @id with parameters [{"name":"id","value":"596ff484-584e-4c2b-a26f-adf89e562258","type":{"length":255}},{"name":"new_user_id","value":"martin","type":{}}]
2016-03-25T10:12:53.385Z - debug: SQL statement failed - Invalid column name 'new_user_id'.: INSERT INTO [dbo].[MyfStorageRooms] ([id],[new_user_id]) VALUES (@id,@new_user_id); SELECT * FROM [dbo].[MyfStorageRooms] WHERE [id] = @id with parameters [{"name":"id","value":"596ff484-584e-4c2b-a26f-adf89e562258","type":{"length":255}},{"name":"new_user_id","value":"martin","type":{}}]
2016-03-25T10:13:26.813Z - info: Updating schema for table MyfStorageRooms
2016-03-25T10:13:26.814Z - silly: Executing SQL statement SELECT COLUMN_NAME AS name, DATA_TYPE AS type FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @table AND TABLE_SCHEMA = @schema with parameters [{"name":"table","value":"MyfStorageRooms"},{"name":"schema","value":"dbo"}]
2016-03-25T10:13:26.896Z - silly: Executing SQL statement ALTER TABLE [dbo].[MyfStorageRooms] ADD [new_user_id] NVARCHAR(MAX) NULL with parameters undefined
2016-03-25T10:13:27.042Z - silly: Executing SQL statement INSERT INTO [dbo].[MyfStorageRooms] ([id],[new_user_id]) VALUES (@id,@new_user_id); SELECT * FROM [dbo].[MyfStorageRooms] WHERE [id] = @id with parameters [{"name":"id","value":"596ff484-584e-4c2b-a26f-adf89e562258","type":{"length":255}},{"name":"new_user_id","value":"martin","type":{}}]
ID 596ff484-584e-4c2b-a26f-adf89e562258 inserted

**Comment by m-andersen** [comment] 2016-03-25 16:59
I have another error, which is still related to the topic I described. Now that the above is working ok for 1 item, having several items that should be inserted fails.
I'm still learning node.js and I did a search on how to do the best async handling when it comes to table operations. One option was to use a Promise. That means:
- create x number of promises, one for each item to insert to the table
- Wait for the promises to finish and then continue

It seems like doing parallel operations when a new column is to be added fails. This can be tricky to fix.
Code is the following in a POST function (here the number of JSON objects in the receive body should be more than 1):

var promises = req.body.map( function(name){
            return new Promise(function(resolve,reject){
                var userID = "martin";
                var dbID = uuid.v4();
                storageRoomTable.insert({ id: dbID, new5_user_id: userID })
                    .then(function () {
                        console.log("ID %s inserted", dbID);
                        resolve();
                    });
            });
        });

Promise.all(promises)
        .then(function() { 
            console.log('real: all entries inserted)'); 
        }).catch(console.error);

It alters the table fine (original problem solved), but since this is done in parallel, it tries to alter it a 2nd time (if there are 2 objects in the request body). Error is

2016-03-25T16:52:25.143Z - silly: Executing SQL statement ALTER TABLE [dbo].[MyfStorageRooms] ADD [new5_user_id] NVARCHAR(MAX) NULL with parameters undefined
2016-03-25T16:52:25.151Z - silly: Executing SQL statement ALTER TABLE [dbo].[MyfStorageRooms] ADD [new5_user_id] NVARCHAR(MAX) NULL with parameters undefined
2016-03-25T16:52:25.270Z - silly: Executing SQL statement INSERT INTO [dbo].[MyfStorageRooms] ([id],[new5_user_id]) VALUES (@id,@new5_user_id); SELECT * FROM [dbo].[MyfStorageRooms] WHERE [id] = @id with parameters [{"name":"id","value":"be26d4af-6e15-4cb2-b31f-657943fee3d4","type":{"length":255}},{"name":"new5_user_id","value":"martin","type":{}}]
2016-03-25T16:52:25.274Z - debug: SQL statement failed - Column names in each table must be unique. Column name 'new5_user_id' in table 'dbo.MyfStorageRooms' is specified more than once.: ALTER TABLE [dbo].[MyfStorageRooms] ADD [new5_user_id] NVARCHAR(MAX) NULL with parameters undefined

Is there a way to fix this?

**Comment by danderson00** [comment] 2016-03-25 17:37
Good point on the error message. I'll raise the log level so it only appears if the log level is set to silly.

As far as your schema goes, I would ensure the schema is created by inserting a single record, or you can explicitly specify columns and use the initialize function to create them. You can see an example of this at https://github.com/Azure/azure-mobile-apps-node/tree/master/samples/seeding-data.

**Comment by danderson00** [comment] 2016-04-19 18:44
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/ffe18652d2842e0abfaa75a82555385d76475ab3

**Closed by danderson00** 2016-04-19 18:44 UTC
Labels: Category-Bug
