### ISSUE TITLE
Authentication/Authorization When Debugging Locally

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-apps-node#275] opened 2015-12-19 14:45 UTC
How does authentication with the Azure Authentication/Authorization service work when running locally and debugging?

Calls to the Mobile Services client ".login" fail as they don't know they should redirect to the hosted URL (they have no knowledge of it, as the URL used to initialize the mobile services client is localhost).

Is there a sample showing this?

**Comment by danderson00** [comment] 2015-12-20 22:25
This is a duplicate of https://github.com/Azure/azure-mobile-apps-node/issues/152.

We are working on providing a substitute piece of middleware for local debugging.

**Closed by danderson00** 2015-12-20 22:25 UTC

**Comment by joewood** [comment] 2015-12-21 01:55
The request was more about adding some documentation of how to do the authentication in the cloud, but use that token locally (rather than 'airplane mode'). Is that supported?

**Comment by danderson00** [comment] 2015-12-21 02:44
It should be. You need to get the WEBSITE_AUTH_SIGNING_KEY environment variable from your SCM endpoint (https://<mobileAppName>.scm.azurewebsites.net/Env) and set the auth.secret configuration setting to that value. Let me know if it doesn't work.

**Comment by joewood** [comment] 2015-12-21 04:11
Great, got that - (that URL is good to know). Unfortunately setting that configuration causes CORS errors. Looking at the responses coming back, when the auth secret is set the Access-Control-Allow-Origin header is not on the response. When I remove it from the configuration the CORS header is set again.

**Comment by joewood** [comment] 2015-12-21 04:23
Thinking about it, this could be intentional to ensure this is used in debug mode only.  The problem I think is that the CORS endpoint includes the port, so running from one port (e.g. localhost:8080 to another localhost:3000) will causes errors without the ACAO header. 

Background - I'm running a webpack-dev-server for the content on one port, and the node.js service on another. I could probably merge this and run webpack inside the ZUMO service in dev mode, it's just easier to keep them separate.
