### ISSUE TITLE
sqlite provider should coerce date types on query input parameters

### ISSUE THREAD

**Issue by chris-armstrong** [Azure/azure-mobile-apps-node#420] opened 2016-05-02 03:56 UTC
On sqlite3, date columns are stored as "TEXT" type. When executing a query, the query parameters need to be specified as a ISO string instead of a JavaScript Date() type to the sqlite3 library for them to work correctly. This means that the `src/data/sqlite/helpers.js` `mapParameters` method ought to do something like this in order to remain coherent with the mssql provider (which passes through Date() types uncoverted to the mssql driver):

```javascript
    mapParameters: function (parameters) {
        return parameters.reduce(function (result, parameter) {
            if (types.isString(parameter.value) || types.isNumber(parameter.value) || typeof parameter.value === 'boolean' ||
                parameter.value === null || parameter.value === undefined) {
                result[parameter.name] = parameter.value;    
            } else if (types.isDate(parameter.value)) {
                result[parameter.name] = parameter.value.toISOString();
            } else {
                throw new Error('Cannot map parameter type: '+parameter.value.constructor)
            }
            
            return result;
        }, {});
    },
```

**Comment by danderson00** [comment] 2016-05-02 21:09
This is essentially a duplicate of https://github.com/Azure/azure-mobile-apps-node/issues/415 but is a much better description. Closing the other issue.

Thanks!

**Comment by danderson00** [comment] 2016-07-13 02:16
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/3459c9848b5763ab3b9502d92bdc93b3d8acee86

**Closed by danderson00** 2016-07-13 02:16 UTC
Labels: Category-Bug, ready
