### ISSUE TITLE
Api customisation

### ISSUE THREAD

**Issue by Mimetis** [Azure/azure-mobile-apps-node#178] opened 2015-11-12 18:24 UTC
I try to implement some customs Apis.
As I have a lot of apis, I would like to do something like this :

Assuming I'm in an achievement.js file (located in the /api folder) 

```Javascript
    api.get('/api/:gameId/achievements/get/:achievementName, exports.getAchievement);
    api.get('/api/:gameId/achievements/all', exports.getAchievements);
    api.get('/api/:gameId/achievements/count', exports.getCount);
    api.post('/api/:gameId/achievements/get', exports.getAchievementPost);
    api.post('/api/:gameId/achievements/set', exports.addOrUpdateAchievement);
    api.post('/api/:gameId/achievements/del', exports.deleteAchievement);

```
I assume I can bypass the api model, but it would be great to integrate such behavior in the SDK, with autorisation and so on...

**Comment by adrianhall** [comment] 2015-11-12 20:53
See also #96

**Comment by paulbatum** [comment] 2015-12-30 21:04
Closing this given it is a dupe of #96.

**Closed by paulbatum** 2015-12-30 21:04 UTC
Labels: Resolution-Duplicate
