### ISSUE TITLE
Add File Sync support to Node server SDK

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-node#421] opened 2016-05-04 18:17 UTC
Should follow the pattern here: https://github.com/Azure/azure-mobile-apps-net-files-server

Tutorial: https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-xamarin-forms-blob-storage/

**Comment by danderson00** [comment] 2016-05-04 18:19
This is a duplicate of https://github.com/Azure/azure-mobile-apps-node/issues/67, but provides a bit more info. Closing the other issue. Will have a chat with you about priority.

**Comment by lindydonna** [comment] 2016-05-04 18:31
@danderson00 You should chat with @adrianhall about priority, since I don't know what other work there is.

**Comment by danderson00** [comment] 2016-06-30 22:38
This is implemented in the Azure/azure-mobile-apps-node-files repo with automatic loading of the plugin implemented in this repo.

**Closed by danderson00** 2016-06-30 22:38 UTC
Labels: Category-Feature Request, in progress, Size-Medium
