### ISSUE TITLE
Enhance support for OData with Navigation Properties and $expand

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-apps-node#95] opened 2015-10-13 17:14 UTC
Richer support for OData would avoid the need to write server side API scripts for queries that involve joining related tables. OData supports this by expressing queries that navigate over the graph of related entities. [OData 2 $expand](http://www.odata.org/documentation/odata-version-2-0/uri-conventions)

**Comment by danderson00** [comment] 2016-07-13 20:48
Duplicate of https://github.com/Azure/azure-mobile-apps-node/issues/455

**Closed by danderson00** 2016-07-13 20:48 UTC
Labels: Category-Feature Request, Resolution-Duplicate, Size-Large
