### ISSUE TITLE
Inserting an item named "_ID" is not written to table

### ISSUE THREAD

**Issue by m-andersen** [Azure/azure-mobile-apps-node#399] opened 2016-04-03 13:06 UTC
If I try to insert an item to SQL table, which has the following field (among others)

{_ID: "1234"}

The value is never written to the table. I checked the code and it seems like all fields which starts with underscore are removed. Is this on purpose, limitation or simply a bug?
I don't read anywhere this is not allowed.

**Comment by danderson00** [comment] 2016-04-04 17:12
Hi @m-andersen, I am unable to reproduce this behavior. Could you point to the line of code you believe is to blame? Thanks!

**Comment by m-andersen** [comment] 2016-04-04 19:14
Hi
Sorry, I read code wrong. It seems to be happening elsewhere in the flow. I can only reproduce that any field I make with an _ infront, will only be created as a new column, but actual value does not get written to the table.
Can you assist with remote debug of this?

**Comment by danderson00** [comment] 2016-04-04 20:29
I'm still unable to reproduce with a simple scenario involving _ prefixes. Can you post your code? Cheers!

**Comment by m-andersen** [comment] 2016-04-04 20:45
I forgot to mention all this is executed via a custom API. This is the essense of the code

var householdsTable = req.azureMobile.tables('MyfHouseholds');

householdWrite(householdsTable, uID, items);
which calls this function:

function householdWrite(householdsTable, userID, items) 
{
    var promise_household_write = items.map( function(elem) {
        return new Promise( function(resolve, reject) {
                         
            householdsTable.insert(elem).then( function (){
                console.log("Inserted new household: ", elem);
                resolve(elem);
            });
        });      
    });
    
    return promise_household_write;
}

Via Postman I post this JSON block
[
{
"_ID": "123456",
"household_name": "test",
"UUID": null
}
]

The _ID is created in the table if not existing, but the value specified is not written. Field is empty in the table. All other fields gets written OK. Only if I remove the underscore, the field gets written. E.g. "newcolumn" works fine but not "_newcolumn"

**Comment by danderson00** [comment] 2016-04-04 21:37
I'm still unable to reproduce this behavior with your code. All columns are inserted as expected. It is worth noting that the value returned by the householdWrite function is an array of promises and you'll need to collapse them into a single promise by doing something like:

    var promises = require('azure-mobile-apps/src/utilities/promises');
    var parallelPromise = promises.all(householdWrite(table, userid, items));

you can then call .then on the parallelPromise object, or return this from a table operation.

**Comment by m-andersen** [comment] 2016-04-04 21:49
Yes, that is also how I do it - waiting for the array of promises to finish, though only one object to process. Even if I take out the table.insert() part and skip all the promise stuff, it still fails.

Promise.all(promisehouseholdWrite).then( function(status) { 
                        console.log("Promise: Done writing info");      
                        res.status(201).send(item);
                    }).catch( function(error) {
                        console.log(error);
                        res.status(500).send(error); 
                    });

I have a work-around to write another field instead of the _ID, but annoying to keep track of.

**Comment by danderson00** [comment] 2016-04-04 22:44
This is very strange. There is certainly no specific code for dealing with general properties with a single underscore prefix. We should be able to narrow down at least where the issue is occurring - if you set the logging level to "silly", you can see the exact SQL statements being executed. You can do this by adding a command line option `---logging.level silly` or adding a logging section to the configuration `{ logging: { level: 'silly' } }. Let me know if the parameters are being created correctly.

**Comment by m-andersen** [comment] 2016-04-04 22:53
This is the SQL output of the insert, where _ID is present, but value doesn't get written to table

`2016-04-04T22:52:35.166Z - silly: Executing SQL statement INSERT INTO [dbo].[MyfHouseholds] ([_ID],[household_name],[id],[owner_id]) VALUES (@_ID,@household_name,@id,@owner_id); SELECT * FROM [dbo].[MyfHouseholds] WHERE [id] = @id with parameters [{"name":"_ID","value":"123456","type":{}},{"name":"household_name","value":"test","type":{}},{"name":"id","value":"4bf68b7a-6439-4e22-b368-8c5f70787946","type":{"length":255}},{"name":"owner_id","value":"sid:3e2d36c26fc1a21973ddae5e8418bc0b","type":{}}]`

**Comment by danderson00** [comment] 2016-04-05 23:58
This is a really strange problem that I cannot reproduce. Are you able to reproduce this with a really simple setup that you can send to us?

**Comment by m-andersen** [comment] 2016-04-06 15:51
I will try with a project from scratch and let you know

**Comment by m-andersen** [comment] 2016-04-06 16:43
I tried with a new mobile app website, created the database connections. Did a simple test to a new table, but same problem. Should I mail you the source files? Note, it is still executed via custom API

**Comment by danderson00** [comment] 2016-04-06 18:24
That would be great - dalander at microsoft.

**Comment by danderson00** [comment] 2016-05-04 20:53
@m-andersen Is this still an issue? I was never able to reproduce this issue.

**Comment by m-andersen** [comment] 2016-05-05 04:56
Hi Dale

I haven’t had the opportunity to try to reproduce on a new clean setup. It is still on my TODO list. I will see if I can get it done next week.

br
Martin

**Comment by danderson00** [comment] 2016-05-05 17:12
No worries, I'll leave this open for now to make sure we follow up.

**Comment by danderson00** [comment] 2016-07-13 02:21
@m-andersen Did you ever sort this out?

**Comment by danderson00** [comment] 2016-07-30 02:02
Closing this issue as unable to reproduce. Please feel free to reopen if you can provide more detail.

**Closed by danderson00** 2016-07-30 02:02 UTC
Labels: blocked, Category-Bug

**Comment by m-andersen** [comment] 2016-08-24 19:04
I finally got to test more. Adding "_id" does generate an ALTER TABLE operation and data is inserted correctly. When reading data using Postman the value is there. Using the Azure portal, I see the column _id but the value that is there is empty. So that was the actual bug.

**Comment by danderson00** [comment] 2016-08-24 21:30
Confirmed there is a bug in the portal here. I've raised an issue in our portal repo. 

@m-andersen Thanks for following up on this, much appreciated!
